version: '3.8'
services:
  computersales.mvc:
    container_name: "computersales.mvc" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:8080"
    restart: always 
     